#---------------------------------------------------#
# 配置文件需要放置在 $HOME/.config/clash/config.yml
# 或者運行目錄下的config.yml
#---------------------------------------------------#
# 混合端口 HTTP和SOCKS5用一個端口
mixed-port: 7890

# HTTP 代理端口
# port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的 redir 代理端口 (如需使用此功能，請取消注釋)
# redir-port: 7892

# 允許局域網的連接（可用來共享代理）
allow-lan: true

# 僅在將allow-lan設置為true時適用
# #"*": 綁定所有IP地址
# #192.168.122.11: 綁定單個IPv4地址
# #"[aaaa::a8aa:ff:fe09:57d8]": 綁定單個IPv6地址
bind-address: "*"
ipv6: true

# 規則模式：rule（規則） / global（全局代理）/ direct（全局直連）/ script (腳本)
# mode: rule

# 設置日誌輸出級別 (默認級別：silent，即不輸出任何內容，以避免因日誌內容過大而導致程序內存溢出）。
# 5 個級別：silent / error / warning / info / debug。級別越高日誌輸出量越大，越傾向於調試，若需要請自行開啓。
log-level: info

# Clash 的 RESTful API
external-controller: '127.0.0.1:9090'

# 您可以將靜態網頁資源（如 clash-dashboard）放置在一個目錄中，clash 將會服務於 `RESTful API/ui`
# 參數應填寫配置目錄的相對路徑或絕對路徑。
# http://127.0.0.1:9090/ui/#/
# external-ui: folder
# yacd面板：  https://github.com/haishanh/yacd
# Razord面板：http://clash.razord.top/#/proxies
# external-ui: dashboard

# RESTful API 的口令 (可選)
# secret: ""

# 實驗性功能
experimental:
  ignore-resolve-fail: true # 忽略 DNS 解析失敗，默認值為 true
  # interface-name: en0 # outbound interface name

# 本地 SOCKS5 / HTTP(S) 服務認證
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# 實驗性功能 hosts, 支持通配符 (例如 *.clash.dev 甚至 *.foo.*.example.com)
# 靜態的域名 比 通配域名 具有更高的優先級 (foo.example.com 優先於 *.example.com)
# 注意: hosts 在 fake-ip 模式下不生效
#hosts:
#   '*.clash.dev': 127.0.0.1
#   'alpha.clash.dev': '::1'

#dns:
  #enable: true # 是否啓用dns false
  #ipv6: false
  #listen: 0.0.0.0:53
  #enhanced-mode: redir-host # 模式：redir-host或fake-ip
  #fake-ip-range: 198.18.0.1/16 #
  #fake-ip-filter: # fake ip 白名單列表，如果你不知道這個參數的作用，請勿修改
     #- '*.lan'
     #- localhost.ptlogin2.qq.com
  #nameserver:
     #- 223.5.5.5 # 阿里DNS
     #- 180.76.76.76 # 百度DNS
     #- 119.29.29.29 # 騰訊DNS
     #- 117.50.11.11 # ONE DNS攔截版 惡意網站攔截、廣告過濾
     #- 117.50.10.10 # ONE DNS純淨版 直接返回其真實的響應結果
     #- 114.114.114.114 # 114DNS
     #- https://dns.alidns.com/dns-query # 阿里 DoH DNS
     #- https://doh.360.cn/dns-query # 360 DoH DNS
  #fallback:
     #- 8.8.8.8 # 谷歌DNS
     #- 1.1.1.1 # Cloudflare DNS
     #- tls://dns.rubyfish.cn:853
     #- tls://1.0.0.1:853
     #- tls://dns.google:853
     #- https://dns.rubyfish.cn/dns-query
     #- https://cloudflare-dns.com/dns-query
     #- https://dns.google/dns-query
  #fallback-filter:
     #geoip: true # 默認
     #ipcidr: # 在這個網段內的 IP 地址會被考慮為被污染的 IP
       #- 240.0.0.0/4

# 1. clash DNS 請求邏輯：
#   (1) 當訪問一個域名時， nameserver 與 fallback 列表內的所有服務器併發請求，得到域名對應的 IP 地址。
#   (2) clash 將選取 nameserver 列表內，解析最快的結果。
#   (3) 若解析結果中，IP 地址屬於 國外，那麼 clash 將選擇 fallback 列表內，解析最快的結果。
#
#   因此，我在 nameserver 和 fallback 內都放置了無污染、解析速度較快的國內 DNS 服務器，以達到最快的解析速度。
#   但是 fallback 列表內服務器會用在解析境外網站，為了結果絕對無污染，我僅保留了支持 DoT/DoH 的兩個服務器。
#
# 2. clash DNS 配置注意事項：
#   (1) 如果您為了確保 DNS 解析結果無污染，請僅保留列表內以 tls:// 或 https:// 開頭的 DNS 服務器，但是通常對於國內域名沒有必要。
#   (2) 如果您不在乎可能解析到污染的結果，更加追求速度。請將 nameserver 列表的服務器插入至 fallback 列表內，並移除重復項。
#
# 3. 關於 DNS over HTTPS (DoH) 和 DNS over TLS (DoT) 的選擇：
#   對於兩項技術雙方各執一詞，而且會無休止的爭論，各有利弊。各位請根據具體需求自行選擇，但是配置文件內默認啓用 DoT，因為目前國內沒有封鎖或管制。
#   DoH: 以 https:// 開頭的 DNS 服務器。擁有更好的偽裝性，且幾乎不可能被運營商或網絡管理封鎖，但查詢效率和安全性可能略低。
#   DoT: 以 tls:// 開頭的 DNS 服務器。擁有更高的安全性和查詢效率，但端口有可能被管制或封鎖。
#   若要瞭解更多關於 DoH/DoT 相關技術，請自行查閱規範文檔。

# 代理組
# 下面這3個不要引到訂閱里去 要不會出錯
# Will be ignored after profile selection
#proxies:
#  - name: Shadowsocks
#    type: socks5
#    server: 127.0.0.1
#    port: 1080
#proxy-groups:
#  - name: Proxy
#    type: select
#    proxies:
#      - Shadowsocks
#rules:
#  - 'MATCH,DIRECT'

# Clash for Windows
# Proxies module latency test settings
cfw-latency-timeout: 3000
cfw-latency-url: http://www.gstatic.com/generate_204

# 混合配置（mixin）
# 支持向所有配置文件中注入公共屬性設置
#cfw-profile-mixin:
  #dns:
    #enable: true
    #listen: :53
    #enhanced-mode: fake-ip
    #nameserver:
     #- 223.5.5.5 # 阿里DNS
     #- 180.76.76.76 # 百度DNS
     #- 119.29.29.29 # 騰訊DNS
     #- 117.50.11.11 # ONE DNS攔截版 惡意網站攔截、廣告過濾
     #- 117.50.10.10 # ONE DNS純淨版 直接返回其真實的響應結果
     #- 114.114.114.114 # 114DNS
  #experimental:
    #interface-name: WLAN

#自定義配置目錄
#cfw-profiles-path: 'C:\Users\Administrator\.config\clash\profiles'

# 打斷連接
# Identify strategy of breaking connections after switching to a new proxy/profile/mode
# Options for proxy: none, chain(proxy group in connection chains), all
# Options for profile: true, false
# Options for mode: true, false
cfw-conn-break-strategy:
  proxy: none # none/chain/all
  profile: true # true/false
  mode: false # true/false

# 自定義狀態欄圖標
#cfw-tray-icon:
#default: .\resources\static\imgs\logo_64.png        # 默認圖標
#system-proxy-on: .\resources\static\imgs\custom.ico   # 開啓系統代理後圖標

# 自定義字體
#cfw-font-family: "Noto Sans TC"   # 系統中存在的字體

# 自定義請求頭
#cfw-http-headers:
  #token: "123456"
  #cfw-version: "0.9.11"

# 自定義節點排序
# 可選參數：
#  default：按配置文件定義節點順序
#  latency：按節點延遲升序排列
#  alphabet：按節點名稱字母表排列
# Sort proxies in Proxies module by default/latency/alphabet
cfw-proxies-order: default

# 子進程 啓動其他應用
# Run child process after CFW started
# Refer: https://docs.cfw.lbyczf.com/contents/childprocess.html
#cfw-child-process:
  # 啓動訂閱轉換程序，端口號7893
  #- command: "subconverter.exe" # run.cmd 程序名稱 subconverter.exe -cfw >>logs/run.log 2>&1
    #args:
      #- "-cfw" # 運行參數1
      #- "-f" # 運行參數2
      #- "pref-acl4ssr.yml" # 運行參數3
    #options:
      #cwd: subconverter # 子進程工作目錄
      #detached: true # 子進程獨立於其父進程運行
      #shell: true # 則在 shell 中運行 command
      #windowsHide: true # 隱藏子進程的控制台窗口
  # 啓動網易雲，端口號3333
  #- command: "unblockneteasemusic.exe" # 啓動網易雲
    #args:
      #- "-p" # 運行參數1
      #- "3333" # 運行參數2
    #options:
      #cwd: unblockNeteaseMusic # 子進程工作目錄
      #detached: true # 子進程獨立於其父進程運行
      #shell: true # 則在 shell 中運行 command
      #windowsHide: true # 隱藏子進程的控制台窗口

# 系統代理跳過列表 cfw-bypass
# System proxy will ignore these domains(or ipnet)
# 系統代理跳過列表-備份的，不起作用，
# 使用時可以將cfw-bypass-bak與cfw-bypass內容互換
cfw-bypass-bak:
  # 原有字段不用刪除
  - qq.com
  - 'music.163.com' # 網易雲域名1
  - '*.music.126.net' # 網易雲域名2
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
# 系統代理跳過列表 起作用的
cfw-bypass:
  # 直連列表
  # MyList
  - "*.13th.tech"
  - "*.423down.com"
  - "*.bokecc.com"
  - "*.chaipip.com"
  - "*.chinaplay.store"
  - "*.hrtsea.com"
  - "*.kaikeba.com"
  - "*.laomo.me"
  - "*.mpyit.com"
  - "*.msftconnecttest.com"
  - "*.msftncsi.com"
  - "*.qupu123.com"
  - "*.pdfwifi.com"
  # CN域名直連
  - "*.cn"
  - "*.中國"
  - "*.公司"
  - "*.網絡"
  # 中國國內常見域名關鍵詞直連
  - "*-cn*"
  - "*360buy*"
  - "*alicdn*"
  - "*alimama*"
  - "*alipay*"
  - "*appzapp*"
  - "*baidupcs*"
  - "*bilibili*"
  - "*ccgslb*"
  - "*chinacache*"
  - "*duobao*"
  - "*duolingo*"
  - "*jdpay*"
  - "*moke*"
  - "*qhimg*"
  - "*vpimg*"
  - "*xiami*"
  - "*xiaomi*"
  # 360
  - "*.360.com"
  - "*.360kuai.com"
  - "*.360safe.com"
  - "*.dhrest.com"
  - "*.qhres.com"
  - "*.qhstatic.com"
  - "*.qhupdate.com"
  - "*.so.com"
  # 4399
  - "*.4399.com"
  - "*.4399pk.com"
  - "*.5054399.com"
  - "*.img4399.com"
  # 58
  - "*.58.com"
  # Alibaba
  - "*.1688.com"
  - "*.aliapp.org"
  - "*.alibaba.com"
  - "*.alibabacloud.com"
  - "*.alibabausercontent.com"
  - "*.alicdn.com"
  - "*.alicloudccp.com"
  - "*.aliexpress.com"
  - "*.aliimg.com"
  - "*.alikunlun.com"
  - "*.alipay.com"
  - "*.alipayobjects.com"
  - "*.alisoft.com"
  - "*.aliyun.com"
  - "*.aliyuncdn.com"
  - "*.aliyuncs.com"
  - "*.aliyundrive.com"
  - "*.amap.com"
  - "*.autonavi.com"
  - "*.dingtalk.com"
  - "*.ele.me"
  - "*.hichina.com"
  - "*.mmstat.com"
  - "*.mxhichina.com"
  - "*.soku.com"
  - "*.taobao.com"
  - "*.taobaocdn.com"
  - "*.tbcache.com"
  - "*.tbcdn.com"
  - "*.tmall.com"
  - "*.tmall.hk"
  - "*.ucweb.com"
  - "*.xiami.com"
  - "*.xiami.net"
  - "*.ykimg.com"
  - "*.youku.com"
  # Baidu
  - "*.baidu.com"
  - "*.baidubcr.com"
  - "*.baidupcs.com"
  - "*.baidustatic.com"
  - "*.bcebos.com"
  - "*.bdimg.com"
  - "*.bdstatic.com"
  - "*.bdurl.net"
  - "*.hao123.com"
  - "*.hao123img.com"
  - "*.jomodns.com"
  - "*.yunjiasu-cdn.net"
  # Bilibili
  - "*.acg.tv"
  - "*.acgvideo.com"
  - "*.b23.tv"
  - "*.bigfun.cn"
  - "*.bigfunapp.cn"
  - "*.biliapi.com"
  - "*.biliapi.net"
  - "*.bilibili.com"
  - "*.biligame.com"
  - "*.biligame.net"
  - "*.bilivideo.com"
  - "*.bilivideo.cn"
  - "*.hdslb.com"
  - "*.im9.com"
  - "*.smtcdns.net"
  # Blizzard
  - "*.battle.net"
  - "*.battlenet.com"
  - "*.blizzard.com"
  # ByteDance
  - "*.bytedance.com"
  - "*.bytedance.net"
  - "*.bytedns.net"
  - "*.byteimg.com"
  - "*.feiliao.com"
  - "*.gifshow.com"
  - "*.huoshan.com"
  - "*.iesdouyin.com"
  - "*.ixigua.com"
  - "*.kspkg.com"
  - "*.pstatp.com"
  - "*.snssdk.com"
  - "*.toutiao.com"
  - "*.toutiao13.com"
  - "*.toutiaocdn.com"
  - "*.toutiaocdn.net"
  - "*.toutiaocloud.com"
  - "*.toutiaohao.com"
  - "*.toutiaohao.net"
  - "*.toutiaoimg.com"
  - "*.toutiaopage.com"
  - "*.wukong.com"
  - "*.zijieimg.com"
  - "*.zjbyte.com"
  - "*.zjcdn.com"
  # CCTV
  - "*.cctv.com"
  - "*.cctvpic.com"
  - "*.livechina.com"
  # ChinaNet
  - "*.21cn.com"
  # DiDi
  - "*.didialift.com"
  - "*.didiglobal.com"
  - "*.udache.com"
  # Douyu 鬥魚
  - "*.douyu.com"
  - "*.douyu.tv"
  - "*.douyuscdn.com"
  - "*.douyutv.com"
  # Epic
  - "*.epicgames.com"
  - "*.helpshift.com"
  - "*.paragon.com"
  - "*.unrealengine.com"
  # HuaWei
  - "*.dbankcdn.com"
  - "*.hc-cdn.com"
  - "*.hicloud.com"
  - "*.huawei.com"
  - "*.huaweicloud.com"
  - "*.huaweishop.net"
  - "*.hwccpc.com"
  - "*.vmall.com"
  - "*.vmallres.com"
  # Iflytek 科大訊飛
  - "*.iflyink.com"
  - "*.iflyrec.com"
  - "*.iflytek.com"
  # Iqiyi
  - "*.71.am"
  - "*.71edge.com"
  - "*.iqiyi.com"
  - "*.iqiyipic.com"
  - "*.ppsimg.com"
  - "*.qiyi.com"
  - "*.qiyipic.com"
  - "*.qy.net"
  # JD
  - "*.360buy.com"
  - "*.360buyimg.com"
  - "*.jcloudcs.com"
  - "*.jd.com"
  - "*.jd.hk"
  - "*.jdcloud.com"
  - "*.jdpay.com"
  - "*.paipai.com"
  # Kingsoft
  - "*.iciba.com"
  - "*.ksosoft.com"
  - "*.ksyun.com"
  # Kuaishou 快手
  - "*.kuaishou.com"
  - "*.yximgs.com"
  # Meitu
  - "*.meitu.com"
  - "*.meitudata.com"
  - "*.meitustat.com"
  - "*.meipai.com"
  # LeTV 樂視
  - "*.le.com"
  - "*.lecloud.com"
  - "*.letv.com"
  - "*.letvcloud.com"
  - "*.letvimg.com"
  - "*.letvlive.com"
  - "*.letvstore.com"
  # MGTV 芒果TV
  - "*.hitv.com"
  - "*.hunantv.com"
  - "*.mgtv.com"
  # MI
  - "*.duokan.com"
  - "*.mi-img.com"
  - "*.mi.com"
  - "*.miui.com"
  - "*.xiaomi.com"
  - "*.xiaomi.net"
  - "*.xiaomicp.com"
  # NetEase
  - "*.126.com"
  - "*.126.net"
  - "*.127.net"
  - "*.163.com"
  - "*.163yun.com"
  - "*.lofter.com"
  - "*.netease.com"
  - "*.ydstatic.com"
  - "*.youdao.com"
  # PPTV、PPLive
  - "*.pplive.com"
  - "*.pptv.com"
  # PDD 拼多多
  - "*.pinduoduo.com"
  - "*.yangkeduo.com"
  # Sina
  - "*.leju.com"
  - "*.miaopai.com"
  - "*.sina.com"
  - "*.sinaapp.com"
  - "*.sinaimg.com"
  - "*.weibo.com"
  - "*.weibocdn.com"
  - "*.xiaoka.tv"
  # Sohu Sogo
  - "*.go2map.com"
  - "*.sogo.com"
  - "*.sogou.com"
  - "*.sogoucdn.com"
  - "*.sohu-inc.com"
  - "*.sohu.com"
  - "*.sohucs.com"
  - "*.sohuno.com"
  - "*.sohurdc.com"
  - "*.v-56.com"
  # Sony
  - "*.playstation.com"
  - "*.playstation.net"
  - "*.playstationnetwork.com"
  - "*.sony.com"
  - "*.sonyentertainmentnetwork.com"
  # SteamCN
  - "*.steamcontent.com"
  - "*.steamusercontent.com"
  - "*.steamchina.com"
  - "csgo.wmsj.cn"
  - "dota2.wmsj.cn"
  - "wmsjsteam.com"
  - "dl.steam.clngaa.com"
  - "dl.steam.ksyna.com"
  - "st.dl.bscstorage.net"
  - "st.dl.eccdnx.com"
  - "st.dl.pinyuncloud.com"
  - "steampipe.steamcontent.tnkjmec.com"
  - "steampowered.com.8686c.com"
  - "steamstatic.com.8686c.com"
  # Tencent
  - "*.foxmail.com"
  - "*.gtimg.com"
  - "*.idqqimg.com"
  - "*.igamecj.com"
  - "*.myapp.com"
  - "*.myqcloud.com"
  - "*.qq.com"
  - "*.qqmail.com"
  - "*.qqurl.com"
  - "*.smtcdns.com"
  - "*.smtcdns.net"
  - "*.soso.com"
  - "*.tencent-cloud.net"
  - "*.tencent.com"
  - "*.tencentmind.com"
  - "*.tenpay.com"
  - "*.wechat.com"
  - "*.weixin.com"
  - "*.weiyun.com"
  # Vip 唯品會
  - "*.appsimg.com"
  - "*.appvipshop.com"
  - "*.vip.com"
  - "*.vipstatic.com"
  # Ximalaya 喜馬拉雅
  - "*.ximalaya.com"
  - "*.xmcdn.com"
  # Xunlei 迅雷
  - "*.00cdn.com"
  - "*.88cdn.com"
  - "*.kanimg.com"
  - "*.kankan.com"
  - "*.p2cdn.com"
  - "*.sandai.net"
  - "*.thundercdn.com"
  - "*.xunlei.com"
  # YYeTs 人人影視
  - "*.got001.com"
  - "*.p4pfile.com"
  - "*.rrys.tv"
  - "*.rrys2020.com"
  - "*.yyets.com"
  - "*.zimuzu.io"
  - "*.zimuzu.tv"
  - "*.zmz001.com"
  - "*.zmz002.com"
  - "*.zmz003.com"
  - "*.zmz004.com"
  - "*.zmz2019.com"
  - "*.zmzapi.com"
  - "*.zmzapi.net"
  - "*.zmzfile.com"
  # Private Tracker
  - "*announce*"
  - "*torrent*"
  - "*tracker*"
  - "*.animebytes.tv"
  - "*.animetorrents.me"
  - "*.awesome-hd.me"
  - "*.beitai.pt"
  - "*.bittorrent.com"
  - "*.broadcasthe.net"
  - "*.chdbits.co"
  - "*.classix-unlimited.co.uk"
  - "*.empornium.me"
  - "*.gazellegames.net"
  - "*.hd4fans.org"
  - "*.hdchina.org"
  - "*.hdhome.org"
  - "*.hdsky.me"
  - "*.hdtime.org"
  - "*.hdzone.me"
  - "*.icetorrent.org"
  - "*.jpopsuki.eu"
  - "*.keepfrds.com"
  - "*.leaguehd.com"
  - "*.m-team.cc"
  - "*.madsrevolution.net"
  - "*.msg.vg"
  - "*.nanyangpt.com"
  - "*.ncore.cc"
  - "*.open.cd"
  - "*.ourbits.club"
  - "*.passthepopcorn.me"
  - "*.privatehd.to"
  - "*.pthome.net"
  - "*.redacted.ch"
  - "*.springsunday.net"
  - "*.tjupt.org"
  - "*.totheglory.im"
  - "*.trontv.com"
  # TeamViewer
  - "*.teamviewer.com"
  # Public Direct CDN 公共直連
  - "*.baomitu.com"
  - "*.bootcss.com"
  - "*.jiasule.com"
  - "*.staticfile.org"
  - "*.upaiyun.com"
  # AccelerateDirectSites
  - "*.10010.com"
  - "*.115.com"
  - "*.12306.com"
  - "*.17173.com"
  - "*.178.com"
  - "*.17k.com"
  - "*.360doc.com"
  - "*.36kr.com"
  - "*.3dmgame.com"
  - "*.51cto.com"
  - "*.51job.com"
  - "*.51jobcdn.com"
  - "*.56.com"
  - "*.8686c.com"
  - "*.abchina.com"
  - "*.abercrombie.com"
  - "*.acfun.tv"
  - "*.air-matters.com"
  - "*.air-matters.io"
  - "*.aixifan.com"
  - "*.algocasts.io"
  - "*.babytree.com"
  - "*.babytreeimg.com"
  - "*.baicizhan.com"
  - "*.baidupan.com"
  - "*.baike.com"
  - "*.biqudu.com"
  - "*.biquge.com"
  - "*.bitauto.com"
  - "*.c-ctrip.com"
  - "*.camera360.com"
  - "*.cdnmama.com"
  - "*.chaoxing.com"
  - "*.che168.com"
  - "*.chinacache.net"
  - "*.chinaso.com"
  - "*.chinaz.com"
  - "*.chinaz.net"
  - "*.chuimg.com"
  - "*.cibntv.net"
  - "*.clouddn.com"
  - "*.cloudxns.net"
  - "*.cn163.net"
  - "*.cnbeta.com"
  - "*.cnbetacdn.com"
  - "*.cnblogs.com"
  - "*.cnki.net"
  - "*.cnmstl.net"
  - "*.coolapk.com"
  - "*.coolapkmarket.com"
  - "*.csdn.net"
  - "*.ctrip.com"
  - "*.dangdang.com"
  - "*.dfcfw.com"
  - "*.dianping.com"
  - "*.dilidili.wang"
  - "*.douban.com"
  - "*.doubanio.com"
  - "*.dpfile.com"
  - "*.duowan.com"
  - "*.dxycdn.com"
  - "*.dytt8.net"
  - "*.easou.com"
  - "*.eastday.com"
  - "*.eastmoney.com"
  - "*.ecitic.com"
  - "*.ewqcxz.com"
  - "*.fang.com"
  - "*.fantasy.tv"
  - "*.feng.com"
  - "*.fengkongcloud.com"
  - "*.fir.im"
  - "*.frdic.com"
  - "*.fresh-ideas.cc"
  - "*.ganji.com"
  - "*.ganjistatic1.com"
  - "*.geetest.com"
  - "*.geilicdn.com"
  - "*.ghpym.com"
  - "*.godic.net"
  - "*.guazi.com"
  - "*.gwdang.com"
  - "*.gzlzfm.com"
  - "*.haibian.com"
  - "*.haosou.com"
  - "*.hollisterco.com"
  - "*.hongxiu.com"
  - "*.huajiao.com"
  - "*.hupu.com"
  - "*.huxiucdn.com"
  - "*.huya.com"
  - "*.ifeng.com"
  - "*.ifengimg.com"
  - "*.images-amazon.com"
  - "*.infzm.com"
  - "*.ipip.net"
  - "*.it168.com"
  - "*.ithome.com"
  - "*.ixdzs.com"
  - "*.jianguoyun.com"
  - "*.jianshu.com"
  - "*.jianshu.io"
  - "*.jianshuapi.com"
  - "*.jiathis.com"
  - "*.jmstatic.com"
  - "*.jumei.com"
  - "*.kaola.com"
  - "*.knewone.com"
  - "*.koowo.com"
  - "*.ksyungslb.com"
  - "*.kuaidi100.com"
  - "*.kugou.com"
  - "*.lancdns.com"
  - "*.landiannews.com"
  - "*.lanzou.com"
  - "*.lanzoui.com"
  - "*.lanzoux.com"
  - "*.lemicp.com"
  - "*.letitfly.me"
  - "*.lizhi.fm"
  - "*.lizhi.io"
  - "*.lizhifm.com"
  - "*.loli.net"
  - "*.luoo.net"
  - "*.lvmama.com"
  - "*.lxdns.com"
  - "*.maoyan.com"
  - "*.meilishuo.com"
  - "*.meituan.com"
  - "*.meituan.net"
  - "*.meizu.com"
  - "*.migucloud.com"
  - "*.miguvideo.com"
  - "*.mobike.com"
  - "*.mogu.com"
  - "*.mogucdn.com"
  - "*.mogujie.com"
  - "*.moji.com"
  - "*.moke.com"
  - "*.msstatic.com"
  - "*.mubu.com"
  - "*.myunlu.com"
  - "*.nruan.com"
  - "*.nuomi.com"
  - "*.onedns.net"
  - "*.onlinedown.net"
  - "*.oracle.com"
  - "*.oschina.net"
  - "*.ourdvs.com"
  - "*.paypal.com"
  - "*.polyv.net"
  - "*.qbox.me"
  - "*.qcloud.com"
  - "*.qcloudcdn.com"
  - "*.qdaily.com"
  - "*.qdmm.com"
  - "*.qhimg.com"
  - "*.qianqian.com"
  - "*.qidian.com"
  - "*.qihucdn.com"
  - "*.qin.io"
  - "*.qiniu.com"
  - "*.qiniucdn.com"
  - "*.qiniudn.com"
  - "*.qiushibaike.com"
  - "*.quanmin.tv"
  - "*.qunar.com"
  - "*.qunarzz.com"
  - "*.rarbg.to"
  - "*.repaik.com"
  - "*.rrmj.tv"
  - "*.ruguoapp.com"
  - "*.runoob.com"
  - "*.sankuai.com"
  - "*.segmentfault.com"
  - "*.sf-express.com"
  - "*.shumilou.net"
  - "*.simplecd.me"
  - "*.sm.ms"
  - "*.smzdm.com"
  - "*.snwx.com"
  - "*.soufunimg.com"
  - "*.sspai.com"
  - "*.startssl.com"
  - "*.suning.com"
  - "*.synology.com"
  - "*.taihe.com"
  - "*.th-sjy.com"
  - "*.tianqi.com"
  - "*.tianqistatic.com"
  - "*.tianyancha.com"
  - "*.tianyaui.com"
  - "*.tietuku.com"
  - "*.tiexue.net"
  - "*.tmiaoo.com"
  - "*.trip.com"
  - "*.ttmeiju.com"
  - "*.tudou.com"
  - "*.tuniu.com"
  - "*.tuniucdn.com"
  - "*.umengcloud.com"
  - "*.upyun.com"
  - "*.uxengine.net"
  - "*.videocc.net"
  - "*.wandoujia.com"
  - "*.weather.com"
  - "*.weico.cc"
  - "*.weidian.com"
  - "*.weiphone.com"
  - "*.weiphone.net"
  - "*.womai.com"
  - "*.wscdns.com"
  - "*.xdrig.com"
  - "*.xhscdn.com"
  - "*.xiachufang.com"
  - "*.xiaohongshu.com"
  - "*.xiaojukeji.com"
  - "*.xinhuanet.com"
  - "*.xip.io"
  - "*.xitek.com"
  - "*.xiumi.us"
  - "*.xslb.net"
  - "*.xueqiu.com"
  - "*.yach.me"
  - "*.yeepay.com"
  - "*.yhd.com"
  - "*.yihaodianimg.com"
  - "*.yinxiang.com"
  - "*.yinyuetai.com"
  - "*.yixia.com"
  - "*.ys168.com"
  - "*.yuewen.com"
  - "*.yy.com"
  - "*.yystatic.com"
  - "*.zealer.com"
  - "*.zhangzishi.cc"
  - "*.zhanqi.tv"
  - "*.zhaopin.com"
  - "*.zhihu.com"
  - "*.zhimg.com"
  - "*.zhongsou.com"
  - "*.zhuihd.com"
  - "localhost"
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
